# Generated by Django 4.1a1 on 2023-04-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Email', models.EmailField(max_length=50)),
                ('Money', models.FloatField()),
                ('Group', models.IntegerField()),
            ],
        ),
    ]
