# Generated by Django 4.1a1 on 2023-05-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_table2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table2',
        ),
    ]
