# Generated by Django 4.1a1 on 2023-05-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_delete_table2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('view', models.TextField()),
                ('live', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
