# Generated by Django 4.1a1 on 2023-05-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_table2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table2',
            old_name='age',
            new_name='age1',
        ),
        migrations.RenameField(
            model_name='table2',
            old_name='live',
            new_name='live1',
        ),
        migrations.RenameField(
            model_name='table2',
            old_name='name',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='table2',
            old_name='view',
            new_name='view1',
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='table2',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
