# Generated by Django 4.1a1 on 2023-05-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_rename_age_table2_age1_rename_live_table2_live1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table2',
        ),
    ]
