# Generated by Django 4.1a1 on 2023-05-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_delete_table2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['id']},
        ),
    ]
