# Generated by Django 4.1a1 on 2023-07-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('quantity_in_pack', models.IntegerField()),
                ('quantity_thing', models.IntegerField()),
                ('packing_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_for_one', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'devices',
            },
        ),
    ]
