# Generated by Django 4.1a1 on 2023-07-14 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.devices'),
        ),
    ]
