# Generated by Django 4.1a1 on 2023-07-20 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_search_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='name',
        ),
    ]
