# Generated by Django 4.1a1 on 2023-05-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('colour', models.TextField()),
                ('calories', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
            ],
        ),
    ]
