# Generated by Django 4.1a1 on 2023-05-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['id']},
        ),
    ]
