# Generated by Django 4.1a1 on 2023-05-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_alter_table_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='calories',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
