# Generated by Django 4.1a1 on 2023-04-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zoo',
            name='name',
            field=models.TextField(),
        ),
    ]
